// <auto-generated />
using DiscordBot.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiscordBot.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250510224238_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("DiscordBot.Database.Entities.EventEntity", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId", "Id");

                    b.ToTable("events");
                });

            modelBuilder.Entity("DiscordBot.Database.Entities.MemberEntity", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CallSign")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<byte?>("RankId")
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("StatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId", "MemberId");

                    b.HasIndex("GuildId", "RankId");

                    b.HasIndex("GuildId", "StatusId");

                    b.ToTable("members");
                });

            modelBuilder.Entity("DiscordBot.Database.Entities.MemberRank", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId", "Id");

                    b.ToTable("ranks");

                    b.HasData(
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Id = (byte)0,
                            Name = "Новобранец",
                            Order = 0
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Id = (byte)1,
                            Name = "Рядовой",
                            Order = 1
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Id = (byte)2,
                            Name = "Капрал",
                            Order = 2
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Id = (byte)3,
                            Name = "Мл Сержант",
                            Order = 3
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Id = (byte)4,
                            Name = "Сержант",
                            Order = 4
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Id = (byte)5,
                            Name = "Ст. Сержант",
                            Order = 5
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Id = (byte)6,
                            Name = "Старшина",
                            Order = 6
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Id = (byte)7,
                            Name = "Прапорщик",
                            Order = 7
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Id = (byte)8,
                            Name = "Ст. Прапорщик",
                            Order = 8
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Id = (byte)9,
                            Name = "Мл. Лейтенант",
                            Order = 9
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Id = (byte)10,
                            Name = "Лейтенант",
                            Order = 10
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Id = (byte)11,
                            Name = "Ст. Лейтенант",
                            Order = 11
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Id = (byte)12,
                            Name = "Капитан",
                            Order = 12
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Id = (byte)13,
                            Name = "Майор",
                            Order = 13
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Id = (byte)14,
                            Name = "Подполковник",
                            Order = 14
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Id = (byte)15,
                            Name = "Полковник",
                            Order = 15
                        });
                });

            modelBuilder.Entity("DiscordBot.Database.Entities.MemberStatus", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId", "Id");

                    b.ToTable("statuses");

                    b.HasData(
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Id = (byte)0,
                            Name = "Неизвестно"
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Id = (byte)1,
                            Name = "Активен"
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Id = (byte)2,
                            Name = "В отпуске"
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Id = (byte)3,
                            Name = "В резерве"
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Id = (byte)4,
                            Name = "Выбыл"
                        });
                });

            modelBuilder.Entity("DiscordBot.Database.Entities.SettingsEntity", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("RegistrationChannelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId");

                    b.ToTable("settings");
                });

            modelBuilder.Entity("DiscordBot.Database.Entities.MemberEntity", b =>
                {
                    b.HasOne("DiscordBot.Database.Entities.MemberRank", "Rank")
                        .WithMany()
                        .HasForeignKey("GuildId", "RankId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DiscordBot.Database.Entities.MemberStatus", "Status")
                        .WithMany()
                        .HasForeignKey("GuildId", "StatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Rank");

                    b.Navigation("Status");
                });
#pragma warning restore 612, 618
        }
    }
}
