// <auto-generated />
using System;
using DiscordBot.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiscordBot.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250511111824_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("DiscordBot.Database.Entities.EventEntity", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("StartTimeSpan")
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId", "Id");

                    b.HasIndex("GuildId", "Id")
                        .IsUnique();

                    b.ToTable("events");
                });

            modelBuilder.Entity("DiscordBot.Database.Entities.MemberEntity", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CallSign")
                        .HasColumnType("TEXT");

                    b.Property<string>("RankName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusName")
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId", "MemberId");

                    b.HasIndex("GuildId", "MemberId")
                        .IsUnique();

                    b.HasIndex("GuildId", "RankName");

                    b.HasIndex("GuildId", "StatusName");

                    b.ToTable("members");
                });

            modelBuilder.Entity("DiscordBot.Database.Entities.MemberRankEntity", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId", "Name");

                    b.HasIndex("GuildId", "Name")
                        .IsUnique();

                    b.HasIndex("GuildId", "Order");

                    b.ToTable("ranks");

                    b.HasData(
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Name = "Новобранец",
                            Order = 0
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Name = "Рядовой",
                            Order = 1
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Name = "Капрал",
                            Order = 2
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Name = "Мл Сержант",
                            Order = 3
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Name = "Сержант",
                            Order = 4
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Name = "Ст. Сержант",
                            Order = 5
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Name = "Старшина",
                            Order = 6
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Name = "Прапорщик",
                            Order = 7
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Name = "Ст. Прапорщик",
                            Order = 8
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Name = "Мл. Лейтенант",
                            Order = 9
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Name = "Лейтенант",
                            Order = 10
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Name = "Ст. Лейтенант",
                            Order = 11
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Name = "Капитан",
                            Order = 12
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Name = "Майор",
                            Order = 13
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Name = "Подполковник",
                            Order = 14
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Name = "Полковник",
                            Order = 15
                        });
                });

            modelBuilder.Entity("DiscordBot.Database.Entities.MemberStatusEntity", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId", "Name");

                    b.HasIndex("GuildId", "Name")
                        .IsUnique();

                    b.ToTable("statuses");

                    b.HasData(
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Name = "Неизвестно"
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Name = "Активен"
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Name = "В отпуске"
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Name = "В резерве"
                        },
                        new
                        {
                            GuildId = 478923127120723969ul,
                            Name = "Выбыл"
                        });
                });

            modelBuilder.Entity("DiscordBot.Database.Entities.SettingsEntity", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("RegistrationChannelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("settings");

                    b.HasData(
                        new
                        {
                            GuildId = 478923127120723969ul,
                            RegistrationChannelId = 1201393133292896286ul
                        });
                });

            modelBuilder.Entity("DiscordBot.Database.Entities.MemberEntity", b =>
                {
                    b.HasOne("DiscordBot.Database.Entities.MemberRankEntity", "Rank")
                        .WithMany()
                        .HasForeignKey("GuildId", "RankName")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DiscordBot.Database.Entities.MemberStatusEntity", "Status")
                        .WithMany()
                        .HasForeignKey("GuildId", "StatusName")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Rank");

                    b.Navigation("Status");
                });
#pragma warning restore 612, 618
        }
    }
}
