// <auto-generated />
using System;
using DiscordBot.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiscordBot.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250524185540_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("DiscordBot.Database.Entities.EventEntity", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreationDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EventDateTime")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId", "Id");

                    b.HasIndex("GuildId", "Id")
                        .IsUnique();

                    b.HasIndex("GuildId", "ChannelId", "MessageId")
                        .IsUnique();

                    b.ToTable("events");
                });

            modelBuilder.Entity("DiscordBot.Database.Entities.EventRepeatabilityEntity", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId", "Id");

                    b.HasIndex("GuildId", "Id")
                        .IsUnique();

                    b.ToTable("event_repeatability");
                });

            modelBuilder.Entity("DiscordBot.Database.Entities.EventTemplateEntity", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreationDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId", "Id");

                    b.HasIndex("GuildId", "Id")
                        .IsUnique();

                    b.ToTable("event_templates");
                });

            modelBuilder.Entity("DiscordBot.Database.Entities.SettingsEntity", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("ScheduleChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("ScheduleMessageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("settings");
                });

            modelBuilder.Entity("DiscordBot.Database.Entities.EventRepeatabilityEntity", b =>
                {
                    b.HasOne("DiscordBot.Database.Entities.EventTemplateEntity", "EventEntity")
                        .WithOne("RepeatabilityEntity")
                        .HasForeignKey("DiscordBot.Database.Entities.EventRepeatabilityEntity", "GuildId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventEntity");
                });

            modelBuilder.Entity("DiscordBot.Database.Entities.EventTemplateEntity", b =>
                {
                    b.Navigation("RepeatabilityEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
